##
# Copyright (c) 2010-2016 Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

# File to configure theming

dev:

preprod:

prod:

all:
  php:
    theme: AdminLTE
    layout: EKA_PACKAGE/package-adminlte/src/AdminLTE/Layout/
